# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=512m
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true

# Android
android.useAndroidX=true
android.enableJetifier=false

# React Native — New Architecture (default true di RN 0.81)
newArchEnabled=true
hermesEnabled=true
